### ISSUE TITLE
Missing user namespace label `user.kubeflow.org/enabled`

### ISSUE THREAD

**Issue by phoevos** [canonical/kubeflow-profiles-operator#127]
Namespaces corresponding to Kubeflow users don't get the `user.kubeflow.org/enabled` label required by default by the Resource Dispatcher to detect the namespaces to inject resources into. 

More specifically, the Resource Dispatcher watches for newly created namespaces. If these carry a specific label (configured by the user), it injects the resources required for its related apps to work into the new namespaces. If the Resource Dispatcher is related with MLFlow, for instance, it will have to create PodDefaults and Secrets in the target namespaces to allow workloads running in them to access external services (e.g. MinIO). This label is essentially used to distinguish namespaces belonging to Kubeflow users and is set by default to [`user.kubeflow.org/enabled: "true"`](https://github.com/canonical/resource-dispatcher/blob/08cba1ab49f867326baba4bd00f49c8b291435d7/config.yaml#L6C1-L9).

The Profiles Operator, on the other hand, is the one that controls the labels that will end up on a new namespace, whenever a Kubeflow user Profile is created, through a YAML file pushed to the controller container. The labels currently propagated to the namespace are configured here: https://github.com/canonical/kubeflow-profiles-operator/blob/e46577ac6d7c7d97c5ddc3e6443a1749f006d305/src/templates/namespace-labels.yaml#L15-L19

It looks like the Profiles Operator should also set the `user.kubeflow.org/enabled: "true"` here, for our services to properly work.

**Comment by ca-scribner** [comment]
For context, the `resource-dispatcher` can watch for any label, so we could use an existing one (maybe `pipelines.kubeflow.org/enabled`).  But adding a new label feels cleaner as its purpose is more clear

**Comment by NohaIhab** [comment]
re-opening this because it was not fixed in `track/1.7`
