### ISSUE TITLE
Unit gets stuck in maintenace status when pebble_ready events occur

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kubeflow-profiles-operator#74]
Event handlers need to be re-designed to reach Active status after handling pebble_ready events.

**Comment by NohaIhab** [comment]
unit reaches active status on install at first, but gets stuck in maintenance in case one of the pebble_ready events take place because their handlers don't call main.

**Comment by i-chvets** [comment]
> unit reaches active status on install at first, but gets stuck in maintenance in case one of the pebble_ready events take place because their handlers don't call main.

At the end of Pebble Ready event we should call main event handler (`main()`).

**Comment by NohaIhab** [comment]
Closing as it's solved by #83
